pyjhoop/AlgorihmStudy

- 박연준/3_1배열과 리스트/Boj11720.java
- 박연준/3_1배열과 리스트/Boj1546.java
- 박연준/3_2구간합/Boj10986.java
- 박연준/3_2구간합/Boj11659.java
- 박연준/3_3투포인터/Boj1940.java
- 박연준/3_3투포인터/Boj2018.java
- 배열과 리스트
- 구간 합
- 투 포인터
골드 이상 문제는 어렵네요 ㅠㅠ
> 박연준/202306.08

- 김현정/11724.연결요소의_개수/11724. 연결요소의 개수.java
- 김현정/11724.연결요소의_개수/11724. 연결요소의 개수.txt
- 김현정/1260.DFS와_BFS.java
- 김현정/13023.ABCDE/13023. ABCDE.java
- 김현정/13023.ABCDE/13023. ABCDE.txt
- 김현정/2023.신기한_소수_찾기.java
- 김현정/2178.미로_탐색.java
- DFS
- BFS
- 한 문제 당 30분 이상으로 시간이 너무 오래 걸린다.
- 경계값이 포함인지 불포함인지 판단이 한번에 안된다.
> 김현정/2023.06.08

- 김현정/백준/11047.동전_0/11047.동전_0(Greedy).java
- 김현정/백준/11047.동전_0/11047.동전_0(구현).java
- 김현정/백준/1715.카드_정렬하기/1715.카드_정렬하기(오답코드).java
- 김현정/백준/1715.카드_정렬하기/1715.카드_정렬하기.java
- 김현정/백준/1744.수_묶기/1744.수_묶기.java
- 김현정/백준/1744.수_묶기/1744.수_묶기.txt
- 김현정/프로그래머스/크레인_인형뽑기_게임.java
> 김현정/2023.06.11

- 김현정/백준/1300.K번째_수.java
- 김현정/백준/1920.수_찾기.java
- 김현정/백준/2343.기타_레슨/2343.기타_레슨.java
- 김현정/백준/2343.기타_레슨/2343.기타_레슨.txt
- 결정 알고리즘(이진탐색)
- 1300 문제에서 주석된 조건이 추가되어서는 안되는 이유를 찾고 있습니다. 혹시 나중에 풀어보시고 이유를 아실 분은 공유 부탁드립니다.
> 김현정/2023.06.10

- 김현정/백준/1541.잃어버린_괄호.java
- 김현정/백준/1931.회의실_배정.java
- 김현정/프로그래머스/괄호_회전하기/괄호_회전하기.java
- 김현정/프로그래머스/괄호_회전하기/괄호_회전하기.txt
- 그리디
- 자료구조(Stack)
- 코드 리뷰 문제 둘 다 스택 구조 코딩문제였네요.
> 김현정/2023.06.12

- 김현정/백준/1929.소수_구하기.java
- 정수론 파트 푸는 중(소수)
- 요즘 시험기간이라 바쁘네요! 그래도 항상 한문제 이상은 풀도록 하겠습니다 
- 내일 좀 많이 푸는 식으로 커버하겠습니다 ㅠㅠ
> 김현정/2023.06.13

- 박연준/5탐색/boj1260.java
- BFS
오늘은 간단하게 BFS에 대해 공부하고 풀어보았습니다.
> 박연준/2023.06.14

- 김현정/백준/1456.거의_소수.java
- 김현정/백준/1747.소수&팰린드롬.java
- 김현정/프로그래머스/가장_큰_수/가장_큰_수.java
- 김현정/프로그래머스/프로세스.java
- 정수론(소수파트)
- 자료구조(Queue)
- 정렬
- ~~새벽에 내일 스터디할 알고리즘 문제 풀고 추가 PR올릴 예정입니다! merge는 익일 AM 6:00 이후에 부탁드립니다.~~(완료)
- <가장 큰 수>는 오래걸렸고  <프로세스>는 비교적 쉽게 푼 것 같습니다
> 김현정/2023.06.14

- 박연준/5탐색/boj1920s1.java
- 박연준/5탐색/boj1920s2.java
- 박연준/코드리뷰 문제/가장큰수.java
- 박연준/코드리뷰 문제/프로세스.java
- 이진탐색
- 우선순위 큐
- 정렬
---- 
복습을 열심히...
> 박연준/2023.06.15

- 김현정/백준/1033.칵테일.java
- 정수론(유클리드호제법, DFS)
- 정수쪽 문제들이 너무 어려워서 진도가 안나가네요 ㅠㅠ
> 김현정/2023.06.16

- 김현정/백준/1016.제곱ㄴㄴ수.java
- 김현정/백준/1850.최대공약수.java
- 김현정/백준/1934.최소공배수.java
- 정수론(유클리드호제법, 소수)
- [1016. 제곱 ㄴㄴ 수] 문제는 정답을 봤는데도 이해가 안가네요. 혹시 이해 되시는 분...
- 오일러 피 파트는 잘 안나온다고도 하고 난이도도 있어보여서 넘겼습니다.
- 저는 수학을 못해서 정수파트가 제일 어려운 것 같습니다
> 김현정/2023.06.15

- 이동복/5_1깊이우선탐색/Boj11724.java
- 이동복/코드리뷰 문제/Solution_0620_01.java
- 이동복/코드리뷰 문제/Solution_0620_02.java
알고리즘
- 깊이 우선 탐색
코드리뷰 2문제
골라주신 코드 리뷰 문제 덕분에 탐색 파트 활용에 도움이 되었습니다.
개인 공부를 하고 알고리즘 문제를 풀다 보니 늘 시간이 부족했었는데 정해진 분량만큼 공부할 수 있도록 하겠습니다!
> 이동복/2023.06.20

- 김현정/프로그래머스/네트워크.java
- 김현정/프로그래머스/타겟_넘버.java
- DFS
- BFS
- 프로그래머스 문제는 둘 다 전형적인 DFS, BFS 문제여서 어렵지 않았습니다.
> 김현정/2023.06.20

- 김현정/백준/1303.전쟁-전투.java
- 김현정/백준/1707.이분_그래프.java
- 김현정/백준/1743.음식물_피하기.java
- 그래프(DFS)
- 실전파트 들어가니 골드 밖에 없어서 너무 어렵네요.
- 오늘 시간이 없어서 책 문제 말고 DFS문제 실버1로 더 풀었습니다.
> 김현정/2023.06.21

- 박연준/5탐색/boj11725.java
- 박연준/5탐색/boj2606.java
- 박연준/5탐색/boj4963.java
- 탐색
--- 
탐색 문제에 대해 부족한 부분이 많아서 복습겸 3문제 풀어봤습니다.
익숙해질 때까지 풀어볼 예정입니다.
> 박연준/2023.06.21

- 이동복/개인문제풀이/스택큐20230620/BOJ11866.java
- 이동복/개인문제풀이/스택큐20230620/PGS올바른괄호.java
- 이동복/개인문제풀이/스택큐20230620/PGS주식가격.java
알고리즘
- 스택/큐
- 문제 파악과 슈도코드 작성하는 능력이 부족한 것 같습니다.
- 다른 분들이 보시기에 몸풀기 정도 되는 문제들로 풀어봤습니다.
탐색 파트 문제를 풀려고 했으나 시간이 너무 오래걸려서 내일 진도로 진행하려고 합니다.
기본 개념을 다시 한번 읽고 책의 문제를 풀어본 후에 알고리즘 사이트 문제를 풀도록 하겠습니다.
> 이동복/2023.06.21

- 박연준/6 그리디/boj1543.java
- 박연준/6 그리디/boj2785.java
- 박연준/6 그리디/boj5585.java
- 그리디 
---
오늘은 그리디에 대한 문제 3문제를 풀어보았습니다.
난이도는 그렇게 어렵진 않았습니다.
> 박연준/2023.06.22

- 이동복/개인문제풀이/탐색20230622/BOJ11724.java
- 이동복/개인문제풀이/탐색20230622/BOJ13023.java
- 이동복/개인문제풀이/탐색20230622/BOJ2023.java
- 이동복/개인문제풀이/탐색20230626/Boj1260.java
알고리즘
-  탐색 관련 3문제 DFS
아직 문제 접근 방식이 어려워 책의 예제와 풀이 위주로 공부했습니다.
문제를 보다보니 조금은 눈에 익은 것 같은데 거의 풀이를 외우다시피 했네요.
다음 파트인 BFS 진도까지 다 진행하면 다른 문제들을 한번 풀어볼 예정입니다.
> 이동복/2023.06.22

- 김현정/백준/1717.집합의_표현.java
- 김현정/백준/1976.여행_가자.java
- 김현정/백준/2251.물통.java
- 그래프(DFS, UnionFind)
- 드디어 그래프 DFS, BFS문제가 끝나고 Union Find 들어갔습니다!
> 김현정/2023.06.22

- 김현정/백준/1043.거짓말/1043.거짓말(리팩토링).java
- 김현정/백준/1043.거짓말/1043.거짓말(책 방법).java
- 김현정/백준/1043.거짓말/1043.거짓말(처음).java
- 김현정/백준/1516.게임_개발.java
- 김현정/백준/2252.줄_세우기.java
- Union Find
- 위상정렬
- 1043이 Union Find의 정수 문제 같습니다. 여러 버전으로 풀어봤네요
> 김현정/2023.06.26
